// admin/src/views/admin/VerificationRequests.vue
<template>
  <v-container fluid>
    <v-row>
      <v-col cols="12">
        <h2 class="text-h4 mb-4">Verification Requests</h2>
        <v-card elevation="2">
          <v-table>
            <thead>
              <tr>
                <th class="text-left">User</th>
                <th class="text-left">Email</th>
                <th class="text-left">ID Photo</th>
                <th class="text-left">Selfie/Photo</th>
                <th class="text-left">Status</th>
                <th class="text-left">Submitted At</th>
                <th class="text-left">Actions</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="request in requests" :key="request._id">
                <td>{{ request.userId?.name || request.userId?.nickname || 'Unknown' }}</td>
                <td>{{ request.userId?.email || 'N/A' }}</td>
                <td>
                  <v-img :src="getFullUrl(request.idUrl)" width="50" height="50" cover class="bg-grey-lighten-2 rounded cursor-pointer" @click="viewImage(getFullUrl(request.idUrl))"></v-img>
                </td>
                <td>
                  <v-img :src="getFullUrl(request.photoUrl)" width="50" height="50" cover class="bg-grey-lighten-2 rounded cursor-pointer" @click="viewImage(getFullUrl(request.photoUrl))"></v-img>
                </td>
                <td>
                  <v-chip :color="getStatusColor(request.status)" size="small">
                    {{ request.status.toUpperCase() }}
                  </v-chip>
                </td>
                <td>{{ new Date(request.submittedAt).toLocaleDateString() }}</td>
                <td>
                  <v-btn v-if="request.status === 'pending'" size="small" color="success" class="mr-2" @click="updateStatus(request._id, 'approved', request.userId?._id)">
                    Approve
                  </v-btn>
                  <v-btn v-if="request.status === 'pending'" size="small" color="error" @click="updateStatus(request._id, 'rejected')">
                    Reject
                  </v-btn>
                  <span v-if="request.status !== 'pending'" class="text-caption text-grey">Processed</span>
                </td>
              </tr>
              <tr v-if="requests.length === 0 && !loading">
                <td colspan="7" class="text-center py-4">No real verification requests found in database.</td>
              </tr>
              <tr v-if="loading">
                <td colspan="7" class="text-center py-4"><v-progress-circular indeterminate color="primary"></v-progress-circular></td>
              </tr>
            </tbody>
          </v-table>
        </v-card>
      </v-col>
    </v-row>

    <!-- Image Dialog -->
    <v-dialog v-model="dialog" max-width="800">
      <v-card>
        <v-card-text class="pa-0">
          <v-img :src="selectedImage" width="100%" contain max-height="80vh"></v-img>
        </v-card-text>
        <v-card-actions>
          <v-spacer></v-spacer>
          <v-btn color="primary" variant="flat" @click="dialog = false">Close</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- Snackbar -->
    <v-snackbar v-model="snackbar" :color="snackbarColor" timeout="3000">
      {{ snackbarText }}
      <template v-slot:actions>
        <v-btn color="white" variant="text" @click="snackbar = false">Close</v-btn>
      </template>
    </v-snackbar>
  </v-container>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import axios from 'axios';

const API_BASE_URL = 'https://kairo-b1i9.onrender.com';

const requests = ref<any[]>([]);
const loading = ref(true);
const dialog = ref(false);
const selectedImage = ref('');
const snackbar = ref(false);
const snackbarText = ref('');
const snackbarColor = ref('success');

const showSnackbar = (text: string, color: string = 'success') => {
  snackbarText.value = text;
  snackbarColor.value = color;
  snackbar.value = true;
};

const getFullUrl = (url: string) => {
  if (!url) return '';
  if (url.startsWith('http')) return url;
  return `${API_BASE_URL}/${url}`;
};

const viewImage = (url: string) => {
  selectedImage.value = url;
  dialog.value = true;
};

const getStatusColor = (status: string) => {
  if (status === 'approved') return 'success';
  if (status === 'rejected') return 'error';
  return 'warning';
};

const fetchRequests = async () => {
  loading.value = true;
  try {
    const response = await axios.get(`${API_BASE_URL}/api/verification`);
    requests.value = response.data || [];
  } catch (error) {
    console.error('Error fetching verification requests:', error);
    showSnackbar('Failed to fetch real-time verification requests.', 'error');
  } finally {
    loading.value = false;
  }
};

const updateStatus = async (id: string, status: string, userId?: string) => {
  try {
    await axios.post(`${API_BASE_URL}/api/verification/${id}/status`, { status });
    
    // If approved, also update User/Host verification status in DB
    if (status === 'approved' && userId) {
      await axios.post(`${API_BASE_URL}/api/admin/users/${userId}/verify`, { isVerified: true });
    }

    const request = requests.value.find(r => r._id === id);
    if (request) request.status = status;
    
    showSnackbar(`Verification request ${status} successfully.`);
  } catch (error) {
    console.error(`Error updating verification status:`, error);
    showSnackbar(`Failed to update verification status.`, 'error');
  }
};

onMounted(() => {
  fetchRequests();
});
</script>

// admin/src/pages/VerificationRequests.tsx
import { useState, useEffect } from "react";
import { CheckCircle, XCircle, Eye } from "lucide-react";
import apiClient from "../api/apiClient";

interface VerificationRequest {
  _id: string;
  userId: {
    _id: string;
    name: string;
    phone: string;
    gender?: string;
    profilePicture?: string;
  } | null;
  photoUrl: string;
  idUrl: string;
  status: string;
  createdAt: string;
}

export default function Verification() {
  const [requests, setRequests] = useState<VerificationRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchRequests = async () => {
    try {
      setError(null);
      const res = await apiClient.get("/admin/verification");
      setRequests(Array.isArray(res.data) ? res.data : []);
    } catch (e) {
      console.error("Failed to fetch verification requests:", e);
      setError(((e as { response?: { data?: { message?: string } } }).response)?.data?.message || "Failed to load requests. Check console for details.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchRequests(); }, []);

  const handleStatus = async (id: string, status: string) => {
    if (!window.confirm(`Are you sure you want to ${status} this request?`)) return;
    try {
      await apiClient.post(`/admin/verification/${id}/status`, { status });
      fetchRequests();
    } catch (e) {
      alert((e as { response?: { data?: { message?: string } } }).response?.data?.message || "Failed to update status");
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Host Verification Requests</h1>
        <button 
          onClick={fetchRequests}
          className="px-4 py-2 bg-brand-50 text-brand-600 text-sm font-bold rounded-xl hover:bg-brand-100 transition-colors"
        >
          Refresh
        </button>
      </div>
      
      {error && (
        <div className="bg-red-50 text-red-600 p-4 rounded-2xl border border-red-100 font-bold">
          ⚠️ {error}
        </div>
      )}

      <div className="bg-white dark:bg-surface-900 rounded-[32px] overflow-hidden shadow-sm border border-gray-100 dark:border-gray-800">
        <table className="w-full text-left">
          <thead className="bg-gray-50 dark:bg-surface-800/50 text-gray-500 text-xs font-bold uppercase tracking-widest border-b border-gray-100 dark:border-gray-800">
            <tr>
              <th className="p-6">User Details</th>
              <th className="p-6">Gender</th>
              <th className="p-6">Verification Files</th>
              <th className="p-6">Status</th>
              <th className="p-6 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100 dark:divide-gray-800">
            {loading ? (<tr><td colSpan={5} className="p-10 text-center text-gray-400 font-medium">Loading requests...</td></tr>) : 
             requests.length === 0 ? (<tr><td colSpan={5} className="p-10 text-center text-gray-500 font-medium">No pending requests found.</td></tr>) :
             requests.map(r => (
              <tr key={r._id} className="hover:bg-gray-50/50 dark:hover:bg-surface-800/30 transition-colors">
                <td className="p-6">
                  <div className="flex items-center gap-3">
                    <img 
                      src={r.userId?.profilePicture || `https://ui-avatars.com/api/?name=${r.userId?.name || "Deleted"}&background=random`} 
                      className="w-10 h-10 rounded-full object-cover border border-gray-100 dark:border-gray-700"
                    />
                    <div>
                      <p className="font-bold text-gray-900 dark:text-white leading-none">{r.userId?.name || "Deleted User"}</p>
                      <p className="text-xs text-gray-400 mt-1">{r.userId?.phone || "N/A"}</p>
                    </div>
                  </div>
                </td>
                <td className="p-6">
                  <span className={`px-2.5 py-1 rounded-lg text-xs font-bold ${
                    r.userId?.gender === "Female" ? "bg-pink-50 text-pink-600" : 
                    r.userId?.gender === "Male" ? "bg-blue-50 text-blue-600" : 
                    "bg-gray-100 text-gray-600"
                  }`}>
                    {r.userId?.gender || "Not Set"}
                  </span>
                </td>
                <td className="p-6">
                  <div className="flex gap-2">
                    <button onClick={() => window.open(r.photoUrl, "_blank")} className="flex items-center gap-1.5 text-brand-600 text-[11px] font-black bg-brand-50 px-3 py-2 rounded-xl hover:bg-brand-100 transition-all border border-brand-100/50">
                      <Eye size={14}/> SELFIE
                    </button>
                    <button onClick={() => window.open(r.idUrl, "_blank")} className="flex items-center gap-1.5 text-blue-600 text-[11px] font-black bg-blue-50 px-3 py-2 rounded-xl hover:bg-blue-100 transition-all border border-blue-100/50">
                      <Eye size={14}/> ID PROOF
                    </button>
                  </div>
                </td>
                <td className="p-6">
                  <span className={`px-3 py-1.5 rounded-full text-[10px] font-black uppercase tracking-wider shadow-sm ${
                    r.status === "pending" ? "bg-orange-100 text-orange-600" : 
                    r.status === "approved" ? "bg-green-100 text-green-600 border border-green-200" : 
                    "bg-red-100 text-red-600 border border-red-200"
                  }`}>
                    {r.status}
                  </span>
                </td>
                <td className="p-6 text-right">
                  <div className="flex justify-end gap-1">
                    {r.status === "pending" ? (
                      <>
                        <button 
                          onClick={() => handleStatus(r._id, "approved")} 
                          className="p-2.5 text-green-600 hover:bg-green-100 rounded-xl transition-all hover:scale-110"
                          title="Approve Host"
                        >
                          <CheckCircle size={22}/>
                        </button>
                        <button 
                          onClick={() => handleStatus(r._id, "rejected")} 
                          className="p-2.5 text-red-600 hover:bg-red-100 rounded-xl transition-all hover:scale-110"
                          title="Reject Request"
                        >
                          <XCircle size={22}/>
                        </button>
                      </>
                    ) : (
                      <span className="text-xs text-gray-400 font-medium italic">Processed</span>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
